version: "3.8"
services:
  entity:
    build: ./entity_service/
    image: gql-demo-entity-service
    ports:
      - "8090:8090"
  search:
    build: ./search_service/
    image: gql-demo-search-service
    ports:
      - "8091:8091"
  image:
    build: ./image_service/
    image: gql-demo-image-service
    ports:
      - "8092:8092"
  deck:
    build: ./deck_service/
    image: gql-demo-deck-service
    ports:
      - "8093:8093"
  apollo-gateway:
    build: ./apollo_gateway/
    image: gql-demo-apollo-gateway
    ports:
      - "4000:4000"
    links:
      - "entity:entityservice"
      - "search:searchservice"
      - "image:imageservice"
      - "deck:deckservice"
    environment:
      ENTITY_HOST: "entityservice:8090"
      SEARCH_HOST: "searchservice:8091"
      IMAGE_HOST: "imageservice:8092"
      DECK_HOST: "deckservice:8093"
      WAIT_HOSTS: entityservice:8090, searchservice:8091, imageservice:8092, deckservice:8093
