micronaut:
  application:
    name: deck
  server:
    port: 8093
---
logger:
  levels:
    deck: DEBUG
---
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
    page-title: GraphiQL
