micronaut:
  application:
    name: entity_service
  server:
    port: 8090
---
logger:
  levels:
    entity: DEBUG
---
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
    page-title: GraphiQL
