micronaut:
  application:
    name: search
  server:
    port: 8091
---
logger:
  levels:
    entity: DEBUG
---
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
    page-title: GraphiQL
