micronaut:
  application:
    name: image
  server:
    port: 8092
---
logger:
  levels:
    entity: DEBUG
---
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
    page-title: GraphiQL
